### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by amirid** [svishwa/crowdcount-cascaded-mtl#1]
Hi,
Could you please share the link to ShanghaiTech dataset?
Thank you in advance.

**Comment by svishwa** [comment]
You can write to the authors - they can share the link.

**Comment by amirid** [comment]
In fact I did and got no response.

**Comment by svishwa** [comment]
The dataset can be downloaded from here:
Dropbox:   https://www.dropbox.com/s/fipgjqxl7uj8hd5/ShanghaiTech.zip?dl=0
Baidu Disk: http://pan.baidu.com/s/1nuAYslz
