### ISSUE TITLE
UC_FF_50 processing code

### ISSUE THREAD

**Issue by asif07hossain** [svishwa/crowdcount-cascaded-mtl#3]
Dear svishwa, I am not getting shanghatitech images publicly. I also emailed to the authors but yet I dint get any kind of links of the dataset. I have UCF dataset. Can you please provide me the UC_FF_50 data processing marlab codes, if available?

**Comment by svishwa** [comment]
The links for shanghai tech dataset are put up on the readme file now.  
There are matlab scripts to process the shanghai tech dataset. You can use the same script to generate the ground truth densities for UCF as well.

**Comment by asif07hossain** [comment]
Dear Concern,

Will you please send me the link of worldexpo'10 dataset and ucsd dataset?

**Comment by asif07hossain** [comment]
Dear Concern,

I really need the ucf_cc_50 , ucsd data set preprocessing code.
If you can send those to me it would help me a lot.
