### ISSUE TITLE
 the output image is grayscale

### ISSUE THREAD

**Issue by Lareinahe** [svishwa/crowdcount-cascaded-mtl#5]
when I run test.py, I found the output image is grayscale while it should be colorful in your paper, what should I do to solve this question.

**Comment by svishwa** [comment]
I generated the color heatmaps in matlab using the outputs from pytorch code.

**Comment by Lareinahe** [comment]
Thank you.

**Comment by ahkarami** [comment]
Dear @svishwa,
Can one generate the color heatmaps (of density maps) via python?
