### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Dangwanli** [svishwa/crowdcount-cascaded-mtl#6]
Hi, I didn't  download the Pre-trained model files [Shanghai Tech A], [Shanghai Tech A],Can you seed me the files to the email, My email is  caacsri_dangwanli@163.com. Thank you  very much

**Comment by svishwa** [comment]
You can download the models from here: 
https://www.dropbox.com/s/irho4laltre9ir5/cmtl_shtechA_204.h5?dl=0
https://www.dropbox.com/s/lkt5ipshibs027w/cmtl_shtechB_768.h5?dl=0

Let me know if you have any issues.

**Comment by Dangwanli** [comment]
svishwa:
Thank you very much. In fact, I can't connect to this site. So I hope you can send this two models to my email. I want to learn this article better thought code. My email is caacsri_dangwanli@163.com,Thank you very much.

**Comment by svishwa** [comment]
Sent!

**Comment by Dangwanli** [comment]
Thank you very much!
